###########################################
experiment_name: pip_32_16_60_r18_l2_l1_10_1_nb10_wcc
data_name: data_300W_CELEBA
det_head: pip
net_stride: 32
batch_size: 16
init_lr: 0.0001
num_epochs: 60
decay_steps: [30, 50]
input_size: 256
backbone: resnet18
pretrained: True
criterion_cls: l2
criterion_reg: l1
cls_loss_weight: 10
reg_loss_weight: 1
num_lms: 68
save_interval: 60
num_nb: 10
use_gpu: True
gpu_id: 4
curriculum: True
###########################################
Epoch 0/59
----------
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\Aaron\anaconda3\envs\nwn2\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "C:\Users\Aaron\anaconda3\envs\nwn2\lib\multiprocessing\spawn.py", line 114, in _main
    prepare(preparation_data)
  File "C:\Users\Aaron\anaconda3\envs\nwn2\lib\multiprocessing\spawn.py", line 225, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\Aaron\anaconda3\envs\nwn2\lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
    run_name="__mp_main__")
  File "C:\Users\Aaron\anaconda3\envs\nwn2\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "C:\Users\Aaron\anaconda3\envs\nwn2\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\Users\Aaron\anaconda3\envs\nwn2\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\project\PIPNet\lib\train_gssl.py", line 162, in <module>
    train_model(cfg.det_head, net, train_loader, criterion_cls, criterion_reg, cfg.cls_loss_weight, cfg.reg_loss_weight, cfg.num_nb, optimizer, cfg.num_epochs, scheduler, save_dir, cfg.save_interval, device)
  File "D:\project\PIPNet\lib\functions_gssl.py", line 149, in train_model
    for i, data in enumerate(train_loader):
  File "C:\Users\Aaron\anaconda3\envs\nwn2\lib\site-packages\torch\utils\data\dataloader.py", line 359, in __iter__
    return self._get_iterator()
  File "C:\Users\Aaron\anaconda3\envs\nwn2\lib\site-packages\torch\utils\data\dataloader.py", line 305, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "C:\Users\Aaron\anaconda3\envs\nwn2\lib\site-packages\torch\utils\data\dataloader.py", line 918, in __init__
    w.start()
  File "C:\Users\Aaron\anaconda3\envs\nwn2\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "C:\Users\Aaron\anaconda3\envs\nwn2\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Users\Aaron\anaconda3\envs\nwn2\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "C:\Users\Aaron\anaconda3\envs\nwn2\lib\multiprocessing\popen_spawn_win32.py", line 33, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "C:\Users\Aaron\anaconda3\envs\nwn2\lib\multiprocessing\spawn.py", line 143, in get_preparation_data
    _check_not_importing_main()
  File "C:\Users\Aaron\anaconda3\envs\nwn2\lib\multiprocessing\spawn.py", line 136, in _check_not_importing_main
    is not going to be frozen to produce an executable.''')
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
###########################################
experiment_name: pip_32_16_60_r18_l2_l1_10_1_nb10_wcc
data_name: data_300W_CELEBA
det_head: pip
net_stride: 32
batch_size: 16
init_lr: 0.0001
num_epochs: 60
decay_steps: [30, 50]
input_size: 256
backbone: resnet18
pretrained: True
criterion_cls: l2
criterion_reg: l1
cls_loss_weight: 10
reg_loss_weight: 1
num_lms: 68
save_interval: 60
num_nb: 10
use_gpu: True
gpu_id: 4
curriculum: True
###########################################
Epoch 0/59
----------
Traceback (most recent call last):
  File "lib/train_gssl.py", line 162, in <module>
    train_model(cfg.det_head, net, train_loader, criterion_cls, criterion_reg, cfg.cls_loss_weight, cfg.reg_loss_weight, cfg.num_nb, optimizer, cfg.num_epochs, scheduler, save_dir, cfg.save_interval, device)
  File "D:\project\PIPNet\lib\functions_gssl.py", line 149, in train_model
    for i, data in enumerate(train_loader):
  File "C:\Users\Aaron\anaconda3\envs\nwn2\lib\site-packages\torch\utils\data\dataloader.py", line 359, in __iter__
    return self._get_iterator()
  File "C:\Users\Aaron\anaconda3\envs\nwn2\lib\site-packages\torch\utils\data\dataloader.py", line 305, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "C:\Users\Aaron\anaconda3\envs\nwn2\lib\site-packages\torch\utils\data\dataloader.py", line 918, in __init__
    w.start()
  File "C:\Users\Aaron\anaconda3\envs\nwn2\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "C:\Users\Aaron\anaconda3\envs\nwn2\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Users\Aaron\anaconda3\envs\nwn2\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "C:\Users\Aaron\anaconda3\envs\nwn2\lib\multiprocessing\popen_spawn_win32.py", line 65, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\Users\Aaron\anaconda3\envs\nwn2\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
BrokenPipeError: [Errno 32] Broken pipe
###########################################
experiment_name: pip_32_16_60_r18_l2_l1_10_1_nb10_wcc
data_name: data_300W_CELEBA
det_head: pip
net_stride: 32
batch_size: 16
init_lr: 0.0001
num_epochs: 60
decay_steps: [30, 50]
input_size: 256
backbone: resnet18
pretrained: True
criterion_cls: l2
criterion_reg: l1
cls_loss_weight: 10
reg_loss_weight: 1
num_lms: 68
save_interval: 60
num_nb: 10
use_gpu: True
gpu_id: 4
curriculum: True
###########################################
Epoch 0/59
----------
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\Aaron\anaconda3\envs\nwn2\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "C:\Users\Aaron\anaconda3\envs\nwn2\lib\multiprocessing\spawn.py", line 114, in _main
    prepare(preparation_data)
  File "C:\Users\Aaron\anaconda3\envs\nwn2\lib\multiprocessing\spawn.py", line 225, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\Aaron\anaconda3\envs\nwn2\lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
    run_name="__mp_main__")
  File "C:\Users\Aaron\anaconda3\envs\nwn2\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "C:\Users\Aaron\anaconda3\envs\nwn2\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\Users\Aaron\anaconda3\envs\nwn2\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\project\PIPNet\lib\train_gssl.py", line 162, in <module>
    train_model(cfg.det_head, net, train_loader, criterion_cls, criterion_reg, cfg.cls_loss_weight, cfg.reg_loss_weight, cfg.num_nb, optimizer, cfg.num_epochs, scheduler, save_dir, cfg.save_interval, device)
  File "D:\project\PIPNet\lib\functions_gssl.py", line 149, in train_model
    for i, data in enumerate(train_loader):
  File "C:\Users\Aaron\anaconda3\envs\nwn2\lib\site-packages\torch\utils\data\dataloader.py", line 359, in __iter__
    return self._get_iterator()
  File "C:\Users\Aaron\anaconda3\envs\nwn2\lib\site-packages\torch\utils\data\dataloader.py", line 305, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "C:\Users\Aaron\anaconda3\envs\nwn2\lib\site-packages\torch\utils\data\dataloader.py", line 918, in __init__
    w.start()
  File "C:\Users\Aaron\anaconda3\envs\nwn2\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "C:\Users\Aaron\anaconda3\envs\nwn2\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Users\Aaron\anaconda3\envs\nwn2\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "C:\Users\Aaron\anaconda3\envs\nwn2\lib\multiprocessing\popen_spawn_win32.py", line 33, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "C:\Users\Aaron\anaconda3\envs\nwn2\lib\multiprocessing\spawn.py", line 143, in get_preparation_data
    _check_not_importing_main()
  File "C:\Users\Aaron\anaconda3\envs\nwn2\lib\multiprocessing\spawn.py", line 136, in _check_not_importing_main
    is not going to be frozen to produce an executable.''')
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
###########################################
experiment_name: pip_32_16_60_r18_l2_l1_10_1_nb10_wcc
data_name: data_300W_CELEBA
det_head: pip
net_stride: 32
batch_size: 16
init_lr: 0.0001
num_epochs: 60
decay_steps: [30, 50]
input_size: 256
backbone: resnet18
pretrained: True
criterion_cls: l2
criterion_reg: l1
cls_loss_weight: 10
reg_loss_weight: 1
num_lms: 68
save_interval: 60
num_nb: 10
use_gpu: True
gpu_id: 4
curriculum: True
###########################################
Epoch 0/59
----------
Traceback (most recent call last):
  File "lib/train_gssl.py", line 162, in <module>
    train_model(cfg.det_head, net, train_loader, criterion_cls, criterion_reg, cfg.cls_loss_weight, cfg.reg_loss_weight, cfg.num_nb, optimizer, cfg.num_epochs, scheduler, save_dir, cfg.save_interval, device)
  File "D:\project\PIPNet\lib\functions_gssl.py", line 149, in train_model
    for i, data in enumerate(train_loader):
  File "C:\Users\Aaron\anaconda3\envs\nwn2\lib\site-packages\torch\utils\data\dataloader.py", line 359, in __iter__
    return self._get_iterator()
  File "C:\Users\Aaron\anaconda3\envs\nwn2\lib\site-packages\torch\utils\data\dataloader.py", line 305, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "C:\Users\Aaron\anaconda3\envs\nwn2\lib\site-packages\torch\utils\data\dataloader.py", line 918, in __init__
    w.start()
  File "C:\Users\Aaron\anaconda3\envs\nwn2\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "C:\Users\Aaron\anaconda3\envs\nwn2\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Users\Aaron\anaconda3\envs\nwn2\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "C:\Users\Aaron\anaconda3\envs\nwn2\lib\multiprocessing\popen_spawn_win32.py", line 65, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\Users\Aaron\anaconda3\envs\nwn2\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
BrokenPipeError: [Errno 32] Broken pipe
###########################################
experiment_name: pip_32_16_60_r18_l2_l1_10_1_nb10_wcc
data_name: data_300W_CELEBA
det_head: pip
net_stride: 32
batch_size: 16
init_lr: 0.0001
num_epochs: 60
decay_steps: [30, 50]
input_size: 256
backbone: resnet18
pretrained: True
criterion_cls: l2
criterion_reg: l1
cls_loss_weight: 10
reg_loss_weight: 1
num_lms: 68
save_interval: 60
num_nb: 10
use_gpu: True
gpu_id: 4
curriculum: True
###########################################
Epoch 0/59
----------
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\Aaron\anaconda3\envs\nwn2\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "C:\Users\Aaron\anaconda3\envs\nwn2\lib\multiprocessing\spawn.py", line 114, in _main
    prepare(preparation_data)
  File "C:\Users\Aaron\anaconda3\envs\nwn2\lib\multiprocessing\spawn.py", line 225, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\Aaron\anaconda3\envs\nwn2\lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
    run_name="__mp_main__")
  File "C:\Users\Aaron\anaconda3\envs\nwn2\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "C:\Users\Aaron\anaconda3\envs\nwn2\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\Users\Aaron\anaconda3\envs\nwn2\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\project\PIPNet\lib\train_gssl.py", line 162, in <module>
    train_model(cfg.det_head, net, train_loader, criterion_cls, criterion_reg, cfg.cls_loss_weight, cfg.reg_loss_weight, cfg.num_nb, optimizer, cfg.num_epochs, scheduler, save_dir, cfg.save_interval, device)
  File "D:\project\PIPNet\lib\functions_gssl.py", line 149, in train_model
    for i, data in enumerate(train_loader):
  File "C:\Users\Aaron\anaconda3\envs\nwn2\lib\site-packages\torch\utils\data\dataloader.py", line 359, in __iter__
    return self._get_iterator()
  File "C:\Users\Aaron\anaconda3\envs\nwn2\lib\site-packages\torch\utils\data\dataloader.py", line 305, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "C:\Users\Aaron\anaconda3\envs\nwn2\lib\site-packages\torch\utils\data\dataloader.py", line 918, in __init__
    w.start()
  File "C:\Users\Aaron\anaconda3\envs\nwn2\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "C:\Users\Aaron\anaconda3\envs\nwn2\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Users\Aaron\anaconda3\envs\nwn2\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "C:\Users\Aaron\anaconda3\envs\nwn2\lib\multiprocessing\popen_spawn_win32.py", line 33, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "C:\Users\Aaron\anaconda3\envs\nwn2\lib\multiprocessing\spawn.py", line 143, in get_preparation_data
    _check_not_importing_main()
  File "C:\Users\Aaron\anaconda3\envs\nwn2\lib\multiprocessing\spawn.py", line 136, in _check_not_importing_main
    is not going to be frozen to produce an executable.''')
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
###########################################
experiment_name: pip_32_16_60_r18_l2_l1_10_1_nb10_wcc
data_name: data_300W_CELEBA
det_head: pip
net_stride: 32
batch_size: 16
init_lr: 0.0001
num_epochs: 60
decay_steps: [30, 50]
input_size: 256
backbone: resnet18
pretrained: True
criterion_cls: l2
criterion_reg: l1
cls_loss_weight: 10
reg_loss_weight: 1
num_lms: 68
save_interval: 60
num_nb: 10
use_gpu: True
gpu_id: 4
curriculum: True
###########################################
Epoch 0/59
----------
Traceback (most recent call last):
  File "lib/train_gssl.py", line 162, in <module>
    train_model(cfg.det_head, net, train_loader, criterion_cls, criterion_reg, cfg.cls_loss_weight, cfg.reg_loss_weight, cfg.num_nb, optimizer, cfg.num_epochs, scheduler, save_dir, cfg.save_interval, device)
  File "D:\project\PIPNet\lib\functions_gssl.py", line 149, in train_model
    for i, data in enumerate(train_loader):
  File "C:\Users\Aaron\anaconda3\envs\nwn2\lib\site-packages\torch\utils\data\dataloader.py", line 359, in __iter__
    return self._get_iterator()
  File "C:\Users\Aaron\anaconda3\envs\nwn2\lib\site-packages\torch\utils\data\dataloader.py", line 305, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "C:\Users\Aaron\anaconda3\envs\nwn2\lib\site-packages\torch\utils\data\dataloader.py", line 918, in __init__
    w.start()
  File "C:\Users\Aaron\anaconda3\envs\nwn2\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "C:\Users\Aaron\anaconda3\envs\nwn2\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Users\Aaron\anaconda3\envs\nwn2\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "C:\Users\Aaron\anaconda3\envs\nwn2\lib\multiprocessing\popen_spawn_win32.py", line 65, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\Users\Aaron\anaconda3\envs\nwn2\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
BrokenPipeError: [Errno 32] Broken pipe
